### PR TITLE
Entity and UserDao

### PR DESCRIPTION
**Pull request by SaifDeveloper**
Entities as per db have been added and createUser method in userDao class

### CODE REVIEW

**Comment by SaifDeveloper** [comment]
postgresql dependency has been added to fix the driver not found error @mavrk

**Comment by mavrk** [comment]
Yeah Saif, I was able to fix it locally too with this. Thanks for including it in the commit though. I'm approving the PR so we can start working on the controllers. Let's merge this.

**Comment by mavrk** [comment]
Feel free to merge whenever you're ready. I'll start writing the controller post that.

**Comment by SaifDeveloper** [comment]
> Feel free to merge whenever you're ready. I'll start writing the controller post that.

@mavrk I have actually almost completed on user sign up, will be raising a PR and will create some issues

**Pull request merged**
